builder_engine:
  author_providers:
    articles:
      author_class:         null
      author_role:          null
      author_placeholder:   id
    pages:
      author_class:         null
      author_role:          null
      author_placeholder:   id
  library_config:
    driver:               local # Required

      # Examples:
      # - local
    # - s3
    max_upload_file:      2M
    service:              null

    # If you are using "s3 driver", you must set this value.
    s3_bucket:            null

    # If you are using "s3 driver", you can set this value to your CDN URL.
    s3_cdn_url:           null
    liip_filter_sets:     []

  # Possible values: default, form
  mode:                 default

  # Full locale name, e.g. "en_US" to use in default locale fields.
  locale_fallback:      en_GB

  # Add a prefix to controllers URLs in "default" mode
  crud_prefix:          /admin

  # Use your own extended template in "default" mode
  extended_template:    '@BuilderEngineInternal/base.html.twig'

  # form_theme to use in builder forms in "default" mode
  form_theme:           '@BuilderEngineInternal/form/builder_form_theme.html.twig'

  # Internal CSS to use with HTML tables in "default" mode
  internal_css:         true

  # Display page title or not in "default" mode
  page_title_display:   true
  pagination_buttons:
    first_button:         '@BuilderEngineInternal/icons/pagination-first.html.twig'
    previous_button:      '@BuilderEngineInternal/icons/pagination-previous.html.twig'
    next_button:          '@BuilderEngineInternal/icons/pagination-next.html.twig'
    last_button:          '@BuilderEngineInternal/icons/pagination-last.html.twig'
  crud_buttons:
    edit_label:           '@BuilderEngineInternal/table/crud-edit.html.twig'
    delete_label:         '@BuilderEngineInternal/table/crud-delete.html.twig'

  # Set customs routes if "default" mode is active.
  custom_routes:
    articles_routes:
      list:                 vzbeb_controller_article_index
      new:                  vzbeb_controller_article_new
      edit:                 vzbeb_controller_article_edit
      delete:               vzbeb_controller_article_delete
    categories_routes:
      list:                 vzbeb_controller_category_index
      new:                  vzbeb_controller_category_new
      edit:                 vzbeb_controller_category_edit
      delete:               vzbeb_controller_category_delete
    pages_routes:
      list:                 vzbeb_controller_page_index
      new:                  vzbeb_controller_page_new
      edit:                 vzbeb_controller_page_edit
      delete:               vzbeb_controller_page_delete
    navigations_routes:
      list:                 vzbeb_controller_navigation_index
      new:                  vzbeb_controller_navigation_new
      edit:                 vzbeb_controller_navigation_edit
      delete:               vzbeb_controller_navigation_delete

  # Set granted roles to allow access to each actions like ["ROLE_USER"] for each controller in "default" mode.
  actions:
    categories:
      new:
        enabled:              true
        roles:                []
      edit:
        enabled:              true
        roles:                []
      delete:
        enabled:              true
        roles:                []
    articles:
      new:
        enabled:              true
        roles:                []
      edit:
        enabled:              true
        roles:                []
      delete:
        enabled:              true
        roles:                []
    pages:
      new:
        enabled:              true
        roles:                []
      edit:
        enabled:              true
        roles:                []
      delete:
        enabled:              true
        roles:                []
    navigations:
      new:
        enabled:              true
        roles:                []
      edit:
        enabled:              true
        roles:                []
      delete:
        enabled:              true
        roles:                []
    libraries:
      delete:
        enabled:              true
        roles:                []