builder_engine:
  author_providers:
    articles:
      author_class:         null
      author_role:          null
      author_placeholder:   id
    pages:
      author_class:         null
      author_role:          null
      author_placeholder:   id
  library_config:
    driver:               local # Required
    service:              null
    liip_filter_sets:     []
  
  # Possible values: default, form
  mode:                 default
  
  # Add a prefix to controllers URLs in "default" mode
  crud_prefix:          /admin
  
  # Use your own extended template in "default" mode
  extended_template:    '@BuilderEngineInternal/base.html.twig'
  
  # form_theme to use in builder forms in "default" mode
  form_theme:           '@BuilderEngineInternal/form/builder_form_theme.html.twig'
  
  # Internal CSS to use with HTML tables in "default" mode
  internal_css:         true
  
  # Display page title or not in "default" mode
  page_title_display:   true
  pagination_buttons:
    first_button:         '@BuilderEngineInternal/icons/pagination-first.html.twig'
    previous_button:      '@BuilderEngineInternal/icons/pagination-previous.html.twig'
    next_button:          '@BuilderEngineInternal/icons/pagination-next.html.twig'
    last_button:          '@BuilderEngineInternal/icons/pagination-last.html.twig'
  crud_buttons:
    edit_label:           '@BuilderEngineInternal/table/crud-edit.html.twig'
    delete_label:         '@BuilderEngineInternal/table/crud-delete.html.twig'
  
  # Set customs routes if "default" mode is active.
  custom_routes:
    articles_routes:
      list:                 xlxeb_controller_article_index
      new:                  xlxeb_controller_article_new
      edit:                 xlxeb_controller_article_edit
      delete:               xlxeb_controller_article_delete
    categories_routes:
      list:                 xlxeb_controller_category_index
      new:                  xlxeb_controller_category_new
      edit:                 xlxeb_controller_category_edit
      delete:               xlxeb_controller_category_delete
    pages_routes:
      list:                 xlxeb_controller_page_index
      new:                  xlxeb_controller_page_new
      edit:                 xlxeb_controller_page_edit
      delete:               xlxeb_controller_page_delete
    navigations_routes:
      list:                 xlxeb_controller_navigation_index
      new:                  xlxeb_controller_navigation_new
      edit:                 xlxeb_controller_navigation_edit
      delete:               xlxeb_controller_navigation_delete
  
  # Set granted roles to allow access to each actions like ["ROLE_USER"] for each controller in "default" mode.
  actions:
    categories:
      new:
        enabled:              true
        roles:                []
      edit:
        enabled:              true
        roles:                []
      delete:
        enabled:              true
        roles:                []
    articles:
      new:
        enabled:              true
        roles:                []
      edit:
        enabled:              true
        roles:                []
      delete:
        enabled:              true
        roles:                []
    pages:
      new:
        enabled:              true
        roles:                []
      edit:
        enabled:              true
        roles:                []
      delete:
        enabled:              true
        roles:                []
    navigations:
      new:
        enabled:              true
        roles:                []
      edit:
        enabled:              true
        roles:                []
      delete:
        enabled:              true
        roles:                []
    libraries:
      delete:
        enabled:              true
        roles:                []
